import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FaLinkedin } from "react-icons/fa";
import Credit from "@/components/Credit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Beyond the Couch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      <Credit/>
      </body>
    </html>
  );
}
